version: "3.8"

services:
  moviesflix-postgres:
    image: postgres:15
    container_name: moviesflix-postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: moviesflix-db
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

moviesflix-pgadmin:
  image: dpage/pgadmin4
  container_name: moviesflix-pgadmin
  restart: always
  depends_on:
    - moviesflix-postgres
  environment:
    - PGADMIN_DEFAULT_EMAIL=user@email.com
    - PGADMIN_DEFAULT_PASSWORD=password
  ports:
    - "5050:80"
  volumes:
    - ./data/pgadmin:/var/lib/pgadmin
